services:
  - type: web
    name: ticket-analyser
    env: node
    buildCommand: npm run build:render
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://ticket-analyser.vercel.app
      - key: MONGODB_URI
        value: mongodb+srv://[jouw-verbindingsstring-hier] 